=== api-evangelist/axway/json-schema/axway-marketplacesettingsupdate-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "#/components/schemas/marketplace.settings.update",
  "title": "marketplace.settings.update",
  "type": "object",
  "description": "Published when marketplace settings are changed.\n\n`subdomain` prop will always be included. Once url is established, `subdomain` prop value will be passed as the `guid`.",
  "x-context": "org",
  "allOf": [
    {
      "$ref": "#/components/schemas/EventDataOrg"
    },
    {
      "$ref": "#/components/schemas/EventDataActor"
    }
  ],
  "properties": {
    "admin_teams": {
      "$ref": "#/components/schemas/Provider/properties/admin_teams"
    },
    "certificate_expires": {
      "$ref": "#/components/schemas/Provider/properties/certificate_expires"
    },
    "changes": {
      "$ref": "#/components/schemas/EventDataChanges"
    },
    "consume_teams": {
      "$ref": "#/components/schemas/Provider/properties/consume_teams"
    },
    "consumer": {
      "$ref": "#/components/schemas/Provider/properties/consumer"
    },
    "consumer_approve": {
      "$ref": "#/components/schemas/Provider/properties/consumer_approve"
    },
    "guid": {
      "$ref": "#/components/schemas/Provider/properties/guid"
    },
    "help_menu": {
      "$ref": "#/components/schemas/Provider/properties/help_menu"
    },
    "idp": {
      "$ref": "#/components/schemas/Provider/properties/idp"
    },
    "idp_hint": {
      "$ref": "#/components/schemas/Provider/properties/idp_hint"
    },
    "lang_default": {
      "$ref": "#/components/schemas/Provider/properties/lang/properties/default"
    },
    "name": {
      "$ref": "#/components/schemas/Provider/properties/name"
    },
    "oauth": {
      "type": "object",
      "properties": {
        "github": {
          "type": "object",
          "properties": {
            "enabled": {
              "$ref": "#/components/schemas/Provider/properties/oauth/properties/github/properties/enabled"
            },
            "secret_updated": {
              "$ref": "#/components/schemas/Provider/properties/oauth/properties/github/properties/secret_updated"
            }
          }
        },
        "gitlab": {
          "type": "object",
          "properties": {
            "enabled": {
              "$ref": "#/components/schemas/Provider/properties/oauth/properties/gitlab/properties/enabled"
            },
            "secret_updated": {
              "$ref": "#/components/schemas/Provider/properties/oauth/properties/gitlab/properties/secret_updated"
            }
          }
        },
        "google": {
          "type": "object",
          "properties": {
            "enabled": {
              "$ref": "#/components/schemas/Provider/properties/oauth/properties/google/properties/enabled"
            },
            "secret_updated": {
              "$ref": "#/components/schemas/Provider/properties/oauth/properties/google/properties/secret_updated"
            }
          }
        }
      },
      "example": {
        "github": {
          "enabled": {},
          "secret_updated": {}
        },
        "gitlab": {
          "enabled": {},
          "secret_updated": {}
        },
        "google": {
          "enabled": {},
          "secret_updated": {}
        }
      }
    },
    "public": {
      "$ref": "#/components/schemas/Provider/properties/public"
    },
    "publish_teams": {
      "$ref": "#/components/schemas/Provider/properties/publish_teams"
    },
    "reviews": {
      "$ref": "#/components/schemas/Provider/properties/reviews"
    },
    "signup": {
      "$ref": "#/components/schemas/Provider/properties/signup"
    },
    "sitename": {
      "$ref": "#/components/schemas/Provider/properties/sitename"
    },
    "subdomain": {
      "$ref": "#/components/schemas/Provider/properties/subdomain"
    },
    "terms": {
      "$ref": "#/components/schemas/Provider/properties/terms"
    },
    "terms_updated": {
      "$ref": "#/components/schemas/Provider/properties/terms_updated"
    },
    "terms_url": {
      "$ref": "#/components/schemas/Provider/properties/terms_url"
    },
    "url": {
      "$ref": "#/components/schemas/Provider/properties/url"
    },
    "versions": {
      "$ref": "#/components/schemas/Provider/properties/versions"
    }
  }
}

=== api-evangelist/axway/examples/amplify-platform-marketplace.create-example.json
{
  "admin_teams": "example_value",
  "certificate_expires": "example_value",
  "consume_teams": "example_value",
  "consumer": "example_value",
  "consumer_approve": "example_value",
  "guid": "507f1f77bcf86cd799439011",
  "help_menu": "example_value",
  "idp": "example_value",
  "idp_hint": "example_value",
  "lang_default": "example_value",
  "name": "Example Name",
  "oauth": {
    "github": {
      "enabled": {},
      "secret_updated": {}
    },
    "gitlab": {
      "enabled": {},
      "secret_updated": {}
    },
    "google": {
      "enabled": {},
      "secret_updated": {}
    }
  },
  "public": "example_value",
  "publish_teams": "example_value",
  "reviews": "example_value",
  "signup": "example_value",
  "sitename": "Example Name",
  "subdomain": "example_value",
  "terms": "example_value",
  "terms_updated": "example_value",
  "terms_url": "https://example.com",
  "url": "https://example.com",
  "versions": "example_value"
}
