=== api-evangelist/axway/json-schema/axway-domain-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "#/components/schemas/Domain",
  "title": "Domain",
  "type": "object",
  "required": [
    "orgs",
    "tld"
  ],
  "unevaluatedProperties": false,
  "allOf": [
    {
      "$ref": "#/components/schemas/DefaultFields"
    }
  ],
  "properties": {
    "_id": {
      "type": "string",
      "description": "Document ID of the Domain.",
      "readOnly": true,
      "deprecated": true,
      "example": "507f1f77bcf86cd799439011"
    },
    "orgs": {
      "type": "array",
      "description": "Organizations associated to this Domain, their association state, and any associated Identity Providers.",
      "default": [],
      "items": {
        "type": "object",
        "required": [
          "guid",
          "status"
        ],
        "additionalProperties": false,
        "properties": {
          "enabled": {
            "type": "string",
            "format": "date-time",
            "description": "Date the Identity Provider was enabled for users on the Domain."
          },
          "associated": {
            "type": "string",
            "format": "date-time",
            "description": "Date the Domain was confirmed as associated to the Identity Provider."
          },
          "guid": {
            "type": "string",
            "format": "uuid",
            "description": "`guid` of the Organization the Domain is associated to."
          },
          "idp": {
            "type": "string",
            "format": "uuid",
            "description": "Identifier of the Identity Provider associated to the Domain for the Organization."
          },
          "status": {
            "type": "number",
            "description": "Indicator of the Organizations confirmed association to the Domain.",
            "enum": [
              0,
              1,
              2,
              3
            ]
          },
          "verified": {
            "type": "string",
            "format": "date-time",
            "description": "Date the Domain was verified as owned by the Organization."
          }
        }
      },
      "example": [
        {
          "enabled": "2026-04-21T00:00:00Z",
          "associated": "2026-04-21T00:00:00Z",
          "guid": "example_value",
          "idp": "example_value",
          "status": 0,
          "verified": "2026-04-21T00:00:00Z"
        }
      ]
    },
    "provider_guid": {
      "type": "string",
      "format": "uuid",
      "description": "GUID identifier of the owning Provider if the Domain is configured in context of consumers of a marketplace.",
      "example": "example_value"
    },
    "tld": {
      "type": "string",
      "format": "domain",
      "description": "Domain name.",
      "example": "example_value"
    }
  }
}

=== api-evangelist/axway/examples/amplify-platform-domain-example.json
{
  "_id": "507f1f77bcf86cd799439011",
  "orgs": [
    {
      "enabled": "2026-04-21T00:00:00Z",
      "associated": "2026-04-21T00:00:00Z",
      "guid": "example_value",
      "idp": "example_value",
      "status": 0,
      "verified": "2026-04-21T00:00:00Z"
    }
  ],
  "provider_guid": "example_value",
  "tld": "example_value"
}
